// GENERATED by tools/gen_mc_tests.mjs from docs/fixtures. Do not edit.

import Toybox.Lang;
import Toybox.Test;

(:test)
function fixture_amrap(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("AMRAP 12\n10 wall balls\n10 burpees\n200m run\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "AMRAP 12", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 720, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "wall_ball", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Wall balls", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 10, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "run", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Run", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 200, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "m", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_amrap_ladder(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("AMRAP 10\n3-6-9-...\nthrusters\nchest to bar\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "AMRAP 10", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], 3, "repStep");
    TestUtil.checkArray(logger, w["repScheme"], [3, 6, 9], "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "thruster", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Thrusters", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "chest_to_bar", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Chest-to-bar", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 0, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_amrap_named(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("# Cindy-ish\n20 min AMRAP\n5 pull-ups\n10 push-ups\n15 air squats\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "Cindy-ish", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 1200, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "pull_up", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Pull-ups", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 5, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "push_up", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Push-ups", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "air_squat", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Air squats", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 15, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "reps", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_amrap_sets_inline(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("3x AMRAP 4 rest 1\n10 wall balls\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "3x AMRAP 4 rest 1", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 240, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], 3, "sets");
    TestUtil.check(logger, w["setRestSec"], 60, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 1, "block count");
    TestUtil.check(logger, b[0]["movement"], "wall_ball", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Wall balls", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 10, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_amrap_task(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("AMRAP 14\n15/12 cal row\n10 burpees\nEvery 3:00, 5 thrusters 40/30\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "AMRAP 14", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 840, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "row", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Row", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 15, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "cal", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], 12, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    var tk = w["task"] as Dictionary;
    TestUtil.check(logger, tk["everySec"], 180, "task everySec");
    TestUtil.check(logger, tk["at0"], false, "task at0");
    var tb = tk["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, tb.size(), 1, "task block count");
    TestUtil.check(logger, tb[0]["movement"], "thruster", "task block 0 movement");
    TestUtil.check(logger, tb[0]["name"], "Thrusters", "task block 0 name");
    TestUtil.check(logger, tb[0]["reps"], 5, "task block 0 reps");
    TestUtil.check(logger, tb[0]["unit"], "reps", "task block 0 unit");
    TestUtil.check(logger, tb[0]["slot"], null, "task block 0 slot");
    TestUtil.checkArray(logger, tb[0]["load"], [40, 30], "task block 0 load");
    TestUtil.check(logger, tb[0]["repsAlt"], null, "task block 0 repsAlt");
    return true;
}

(:test)
function fixture_death_by(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("# Death by burpees\nDEATH BY burpees\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "Death by burpees", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 3600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 60, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 60, "rounds");
    TestUtil.check(logger, w["repStep"], 1, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 1, "block count");
    TestUtil.check(logger, b[0]["movement"], "burpee", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Burpees", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 1, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_death_by_pair(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("Death by: 2 thrusters + 1 burpee\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "Death by: 2 thrusters + 1 burpee", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 3600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 60, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 60, "rounds");
    TestUtil.check(logger, w["repStep"], 2, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "thruster", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Thrusters", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 2, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 1, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 0, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_e2mom_combo(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("E2MOM 20\n5 power cleans (80/55kg) + 10 box jumps\n15 cal row\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "E2MOM 20", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 1200, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 120, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 10, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "power_clean", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Power cleans", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 5, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.checkArray(logger, b[0]["load"], [80, 55], "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "box_jump", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Box jumps", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 0, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "row", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Row", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 15, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "cal", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], 1, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_emom(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("EMOM 10\nodd: 12 kb swings\neven: 10 burpees\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "EMOM 10", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 60, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 10, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "kb_swing", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "KB swings", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 12, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 1, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_emom_min(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("EMOM 12\nmin 1: 15 wall balls\nmin 2: 12 alt db snatches\nmin 3: 30s plank\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "EMOM 12", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 720, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 60, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 12, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "wall_ball", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Wall balls", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 15, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "db_snatch", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "DB snatches", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 12, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 1, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "plank", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Plank", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 30, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "sec", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], 2, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_every(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("EVERY 2:30 x 6\n5 power cleans (80/55kg)\n10 box jumps\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "EVERY 2:30 x 6", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 900, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 150, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 6, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "power_clean", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Power cleans", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 5, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.checkArray(logger, b[0]["load"], [80, 55], "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "box_jump", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Box jumps", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 1, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_every_sec(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("every 90 sec for 12 min\n10 burpees\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "every 90 sec for 12 min", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 720, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 90, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 8, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 1, "block count");
    TestUtil.check(logger, b[0]["movement"], "burpee", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Burpees", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 10, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_for_time(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("FOR TIME cap 15\n21-15-9\nthrusters\npull-ups\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "FOR TIME cap 15", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], 900, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 3, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.checkArray(logger, w["repScheme"], [21, 15, 9], "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "thruster", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Thrusters", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "pull_up", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Pull-ups", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 0, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_for_time_single(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("FOR TIME\n1 km run\n50 double unders\n100 air squats\nfarmer carry 50m\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "FOR TIME", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], null, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 1, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 4, "block count");
    TestUtil.check(logger, b[0]["movement"], "run", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Run", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 1000, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "m", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "double_under", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Double-unders", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 50, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "air_squat", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Air squats", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 100, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "reps", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, b[3]["movement"], "custom", "block 3 movement");
    TestUtil.check(logger, b[3]["name"], "Farmer carry", "block 3 name");
    TestUtil.check(logger, b[3]["reps"], 50, "block 3 reps");
    TestUtil.check(logger, b[3]["unit"], "m", "block 3 unit");
    TestUtil.check(logger, b[3]["slot"], null, "block 3 slot");
    TestUtil.check(logger, b[3]["load"], null, "block 3 load");
    TestUtil.check(logger, b[3]["repsAlt"], null, "block 3 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_hwpo_sets(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("# Skill AMRAP\n3 x AMRAP 1:15\nTough Set Of Strict Handstand Push Up\nTough Set Of Ring Dip (Kipping)\nIn Remaining Time, Max Dual Dumbbell Overhead Hold\nRest 3:00 Between Sets\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "Skill AMRAP", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 75, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], 3, "sets");
    TestUtil.check(logger, w["setRestSec"], 180, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "handstand_push_up", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Strict handstand push up", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "ring_dip", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Ring dips", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 0, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "custom", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Dual dumbbell overhead hold", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 0, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "sec", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_hwpo_task(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("# Ring Push-Up\nFor Time\n50 Ring Push-Up\nEvery minute on the minute (including 0:00), complete 8/6 Cal Ski\nCap : 10:00\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "Ring Push-Up", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], 600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 1, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 1, "block count");
    TestUtil.check(logger, b[0]["movement"], "ring_push_up", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Ring push-ups", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 50, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    var tk = w["task"] as Dictionary;
    TestUtil.check(logger, tk["everySec"], 60, "task everySec");
    TestUtil.check(logger, tk["at0"], true, "task at0");
    var tb = tk["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, tb.size(), 1, "task block count");
    TestUtil.check(logger, tb[0]["movement"], "ski", "task block 0 movement");
    TestUtil.check(logger, tb[0]["name"], "Ski erg", "task block 0 name");
    TestUtil.check(logger, tb[0]["reps"], 8, "task block 0 reps");
    TestUtil.check(logger, tb[0]["unit"], "cal", "task block 0 unit");
    TestUtil.check(logger, tb[0]["slot"], null, "task block 0 slot");
    TestUtil.check(logger, tb[0]["load"], null, "task block 0 load");
    TestUtil.check(logger, tb[0]["repsAlt"], 6, "task block 0 repsAlt");
    return true;
}

(:test)
function fixture_loads_kg(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("FOR TIME\n21-15-9\nthrusters 43/30\n12 kb swings (24)\n10 deadlifts @100\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "FOR TIME", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], null, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 3, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.checkArray(logger, w["repScheme"], [21, 15, 9], "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "thruster", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Thrusters", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.checkArray(logger, b[0]["load"], [43, 30], "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "kb_swing", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "KB swings", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 12, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.checkArray(logger, b[1]["load"], [24], "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "deadlift", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Deadlifts", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 10, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "reps", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.checkArray(logger, b[2]["load"], [100], "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_one_line(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("AMRAP 12; 10 wall balls (9/6kg); 10 burpees; 200m run");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "AMRAP 12", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 720, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "wall_ball", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Wall balls", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 10, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.checkArray(logger, b[0]["load"], [9, 6], "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "run", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Run", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 200, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "m", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_rest_block(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("5 rounds for time\n400m run\n15 kb swings 24/16\nRest 1:00\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "5 rounds for time", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], null, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 5, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "run", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Run", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 400, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "m", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "kb_swing", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "KB swings", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 15, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.checkArray(logger, b[1]["load"], [24, 16], "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "custom", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Rest", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 60, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "sec", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_rft(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("3 ROUNDS FOR TIME (time cap 20:00)\n400m run\n21 KB swings 24/16kg\n12 pull ups\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "3 ROUNDS FOR TIME (time cap 20:00)", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], 1200, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 3, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "run", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Run", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 400, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "m", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "kb_swing", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "KB swings", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 21, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.checkArray(logger, b[1]["load"], [24, 16], "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, b[2]["movement"], "pull_up", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Pull-ups", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 12, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "reps", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.check(logger, b[2]["load"], null, "block 2 load");
    TestUtil.check(logger, b[2]["repsAlt"], null, "block 2 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_tabata(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("TABATA 8x20/10\nair squats\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "TABATA 8x20/10", "name");
    TestUtil.check(logger, w["type"], "TABATA", "type");
    TestUtil.check(logger, w["timeCapSec"], 230, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 30, "intervalSec");
    TestUtil.check(logger, w["workSec"], 20, "workSec");
    TestUtil.check(logger, w["restSec"], 10, "restSec");
    TestUtil.check(logger, w["rounds"], 8, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 1, "block count");
    TestUtil.check(logger, b[0]["movement"], "air_squat", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Air squats", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

(:test)
function fixture_tabata_default(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("TABATA\nair squats\npush-ups\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "TABATA", "name");
    TestUtil.check(logger, w["type"], "TABATA", "type");
    TestUtil.check(logger, w["timeCapSec"], 230, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 30, "intervalSec");
    TestUtil.check(logger, w["workSec"], 20, "workSec");
    TestUtil.check(logger, w["restSec"], 10, "restSec");
    TestUtil.check(logger, w["rounds"], 8, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    TestUtil.check(logger, w["sets"], null, "sets");
    TestUtil.check(logger, w["setRestSec"], null, "setRestSec");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "air_squat", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Air squats", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[0]["load"], null, "block 0 load");
    TestUtil.check(logger, b[0]["repsAlt"], null, "block 0 repsAlt");
    TestUtil.check(logger, b[1]["movement"], "push_up", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Push-ups", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 0, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 1, "block 1 slot");
    TestUtil.check(logger, b[1]["load"], null, "block 1 load");
    TestUtil.check(logger, b[1]["repsAlt"], null, "block 1 repsAlt");
    TestUtil.check(logger, w["task"], null, "task");
    return true;
}

