// GENERATED by tools/gen_mc_tests.mjs from docs/fixtures. Do not edit.

import Toybox.Lang;
import Toybox.Test;

(:test)
function fixture_amrap(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("AMRAP 12\n10 wall balls\n10 burpees\n200m run\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "AMRAP 12", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 720, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "wall_ball", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Wall balls", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 10, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[2]["movement"], "run", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Run", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 200, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "m", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    return true;
}

(:test)
function fixture_amrap_ladder(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("AMRAP 10\n3-6-9-...\nthrusters\nchest to bar\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "AMRAP 10", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], 3, "repStep");
    TestUtil.checkArray(logger, w["repScheme"], [3, 6, 9], "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "thruster", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Thrusters", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "chest_to_bar", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Chest-to-bar", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 0, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    return true;
}

(:test)
function fixture_amrap_named(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("# Cindy-ish\n20 min AMRAP\n5 pull-ups\n10 push-ups\n15 air squats\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "Cindy-ish", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 1200, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "pull_up", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Pull-ups", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 5, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "push_up", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Push-ups", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[2]["movement"], "air_squat", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Air squats", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 15, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "reps", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    return true;
}

(:test)
function fixture_death_by(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("# Death by burpees\nDEATH BY burpees\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "Death by burpees", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 3600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 60, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 60, "rounds");
    TestUtil.check(logger, w["repStep"], 1, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 1, "block count");
    TestUtil.check(logger, b[0]["movement"], "burpee", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Burpees", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 1, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    return true;
}

(:test)
function fixture_death_by_pair(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("Death by: 2 thrusters + 1 burpee\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "Death by: 2 thrusters + 1 burpee", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 3600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 60, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 60, "rounds");
    TestUtil.check(logger, w["repStep"], 2, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "thruster", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Thrusters", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 2, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 1, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 0, "block 1 slot");
    return true;
}

(:test)
function fixture_e2mom_combo(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("E2MOM 20\n5 power cleans (80/55kg) + 10 box jumps\n15 cal row\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "E2MOM 20", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 1200, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 120, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 10, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "power_clean", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Power cleans", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 5, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "box_jump", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Box jumps", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 0, "block 1 slot");
    TestUtil.check(logger, b[2]["movement"], "row", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Row", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 15, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "cal", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], 1, "block 2 slot");
    return true;
}

(:test)
function fixture_emom(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("EMOM 10\nodd: 12 kb swings\neven: 10 burpees\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "EMOM 10", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 600, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 60, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 10, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "kb_swing", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "KB swings", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 12, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 1, "block 1 slot");
    return true;
}

(:test)
function fixture_emom_min(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("EMOM 12\nmin 1: 15 wall balls\nmin 2: 12 alt db snatches\nmin 3: 30s plank\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "EMOM 12", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 720, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 60, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 12, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "wall_ball", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Wall balls", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 15, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "db_snatch", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "DB snatches", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 12, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 1, "block 1 slot");
    TestUtil.check(logger, b[2]["movement"], "plank", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Plank", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 30, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "sec", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], 2, "block 2 slot");
    return true;
}

(:test)
function fixture_every(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("EVERY 2:30 x 6\n5 power cleans (80/55kg)\n10 box jumps\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "EVERY 2:30 x 6", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 900, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 150, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 6, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "power_clean", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Power cleans", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 5, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "box_jump", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Box jumps", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 1, "block 1 slot");
    return true;
}

(:test)
function fixture_every_sec(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("every 90 sec for 12 min\n10 burpees\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "every 90 sec for 12 min", "name");
    TestUtil.check(logger, w["type"], "EMOM", "type");
    TestUtil.check(logger, w["timeCapSec"], 720, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 90, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 8, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 1, "block count");
    TestUtil.check(logger, b[0]["movement"], "burpee", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Burpees", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 10, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    return true;
}

(:test)
function fixture_for_time(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("FOR TIME cap 15\n21-15-9\nthrusters\npull-ups\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "FOR TIME cap 15", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], 900, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 3, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.checkArray(logger, w["repScheme"], [21, 15, 9], "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "thruster", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Thrusters", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "pull_up", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Pull-ups", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 0, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    return true;
}

(:test)
function fixture_for_time_single(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("FOR TIME\n1 km run\n50 double unders\n100 air squats\nfarmer carry 50m\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "FOR TIME", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], null, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 1, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 4, "block count");
    TestUtil.check(logger, b[0]["movement"], "run", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Run", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 1000, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "m", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "double_under", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Double-unders", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 50, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[2]["movement"], "air_squat", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Air squats", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 100, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "reps", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    TestUtil.check(logger, b[3]["movement"], "custom", "block 3 movement");
    TestUtil.check(logger, b[3]["name"], "Farmer carry", "block 3 name");
    TestUtil.check(logger, b[3]["reps"], 50, "block 3 reps");
    TestUtil.check(logger, b[3]["unit"], "m", "block 3 unit");
    TestUtil.check(logger, b[3]["slot"], null, "block 3 slot");
    return true;
}

(:test)
function fixture_one_line(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("AMRAP 12; 10 wall balls (9/6kg); 10 burpees; 200m run");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "AMRAP 12", "name");
    TestUtil.check(logger, w["type"], "AMRAP", "type");
    TestUtil.check(logger, w["timeCapSec"], 720, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], null, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "wall_ball", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Wall balls", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 10, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "burpee", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Burpees", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 10, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[2]["movement"], "run", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Run", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 200, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "m", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    return true;
}

(:test)
function fixture_rft(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("3 ROUNDS FOR TIME (time cap 20:00)\n400m run\n21 KB swings 24/16kg\n12 pull ups\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "3 ROUNDS FOR TIME (time cap 20:00)", "name");
    TestUtil.check(logger, w["type"], "FOR_TIME", "type");
    TestUtil.check(logger, w["timeCapSec"], 1200, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], null, "intervalSec");
    TestUtil.check(logger, w["workSec"], null, "workSec");
    TestUtil.check(logger, w["restSec"], null, "restSec");
    TestUtil.check(logger, w["rounds"], 3, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 3, "block count");
    TestUtil.check(logger, b[0]["movement"], "run", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Run", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 400, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "m", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], null, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "kb_swing", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "KB swings", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 21, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], null, "block 1 slot");
    TestUtil.check(logger, b[2]["movement"], "pull_up", "block 2 movement");
    TestUtil.check(logger, b[2]["name"], "Pull-ups", "block 2 name");
    TestUtil.check(logger, b[2]["reps"], 12, "block 2 reps");
    TestUtil.check(logger, b[2]["unit"], "reps", "block 2 unit");
    TestUtil.check(logger, b[2]["slot"], null, "block 2 slot");
    return true;
}

(:test)
function fixture_tabata(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("TABATA 8x20/10\nair squats\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "TABATA 8x20/10", "name");
    TestUtil.check(logger, w["type"], "TABATA", "type");
    TestUtil.check(logger, w["timeCapSec"], 230, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 30, "intervalSec");
    TestUtil.check(logger, w["workSec"], 20, "workSec");
    TestUtil.check(logger, w["restSec"], 10, "restSec");
    TestUtil.check(logger, w["rounds"], 8, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 1, "block count");
    TestUtil.check(logger, b[0]["movement"], "air_squat", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Air squats", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    return true;
}

(:test)
function fixture_tabata_default(logger as Test.Logger) as Boolean {
    var r = WodParser.parse("TABATA\nair squats\npush-ups\n");
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
    TestUtil.check(logger, w["name"], "TABATA", "name");
    TestUtil.check(logger, w["type"], "TABATA", "type");
    TestUtil.check(logger, w["timeCapSec"], 230, "timeCapSec");
    TestUtil.check(logger, w["intervalSec"], 30, "intervalSec");
    TestUtil.check(logger, w["workSec"], 20, "workSec");
    TestUtil.check(logger, w["restSec"], 10, "restSec");
    TestUtil.check(logger, w["rounds"], 8, "rounds");
    TestUtil.check(logger, w["repStep"], null, "repStep");
    TestUtil.check(logger, w["repScheme"], null, "repScheme");
    var b = w["blocks"] as Array<Dictionary>;
    TestUtil.check(logger, b.size(), 2, "block count");
    TestUtil.check(logger, b[0]["movement"], "air_squat", "block 0 movement");
    TestUtil.check(logger, b[0]["name"], "Air squats", "block 0 name");
    TestUtil.check(logger, b[0]["reps"], 0, "block 0 reps");
    TestUtil.check(logger, b[0]["unit"], "reps", "block 0 unit");
    TestUtil.check(logger, b[0]["slot"], 0, "block 0 slot");
    TestUtil.check(logger, b[1]["movement"], "push_up", "block 1 movement");
    TestUtil.check(logger, b[1]["name"], "Push-ups", "block 1 name");
    TestUtil.check(logger, b[1]["reps"], 0, "block 1 reps");
    TestUtil.check(logger, b[1]["unit"], "reps", "block 1 unit");
    TestUtil.check(logger, b[1]["slot"], 1, "block 1 slot");
    return true;
}

