// GENERATED by tools/make_icons.py. Do not edit.

import Toybox.Lang;

module IconRes {

    function id(name as String) as ResourceId? {
        if (name.equals("ball")) { return Rez.Drawables.Icon_ball; }
        if (name.equals("kb")) { return Rez.Drawables.Icon_kb; }
        if (name.equals("db")) { return Rez.Drawables.Icon_db; }
        if (name.equals("barbell")) { return Rez.Drawables.Icon_barbell; }
        if (name.equals("burpee")) { return Rez.Drawables.Icon_burpee; }
        if (name.equals("pull")) { return Rez.Drawables.Icon_pull; }
        if (name.equals("squat")) { return Rez.Drawables.Icon_squat; }
        if (name.equals("box")) { return Rez.Drawables.Icon_box; }
        if (name.equals("rope")) { return Rez.Drawables.Icon_rope; }
        if (name.equals("climb")) { return Rez.Drawables.Icon_climb; }
        if (name.equals("row")) { return Rez.Drawables.Icon_row; }
        if (name.equals("run")) { return Rez.Drawables.Icon_run; }
        if (name.equals("bike")) { return Rez.Drawables.Icon_bike; }
        if (name.equals("ski")) { return Rez.Drawables.Icon_ski; }
        if (name.equals("hold")) { return Rez.Drawables.Icon_hold; }
        if (name.equals("m_play")) { return Rez.Drawables.Icon_m_play; }
        if (name.equals("m_list")) { return Rez.Drawables.Icon_m_list; }
        if (name.equals("m_stats")) { return Rez.Drawables.Icon_m_stats; }
        if (name.equals("m_coach")) { return Rez.Drawables.Icon_m_coach; }
        if (name.equals("m_sync")) { return Rez.Drawables.Icon_m_sync; }
        if (name.equals("m_star")) { return Rez.Drawables.Icon_m_star; }
        if (name.equals("m_quick")) { return Rez.Drawables.Icon_m_quick; }
        return null;
    }
}
