#!/usr/bin/env python3
"""Generate the movement catalog for the web editor and the watch app.

Source of truth: docs/movements.json
Outputs:
  web-editor/js/movements.js
  watch-app/source/model/MovementCatalog.mc

Run from the repo root:  python3 tools/gen_movements.py
Use --check in CI to fail when generated files are stale.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "movements.json"
JS_OUT = ROOT / "web-editor" / "js" / "movements.js"
MC_OUT = ROOT / "watch-app" / "source" / "model" / "MovementCatalog.mc"

HEADER = "GENERATED by tools/gen_movements.py from docs/movements.json. Do not edit."


def normalize(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[-_.]", " ", s)
    return " ".join(s.split())


def load():
    data = json.loads(SRC.read_text())
    movements = data["movements"]
    ids = set()
    aliases = {}
    for m in movements:
        if not re.fullmatch(r"[a-z][a-z0-9_]*", m["id"]):
            sys.exit(f"bad id {m['id']}")
        if m["id"] in ids:
            sys.exit(f"duplicate id {m['id']}")
        ids.add(m["id"])
        for a in m["aliases"] + [m["name"]]:
            n = normalize(a)
            if n in aliases and aliases[n] != m["id"]:
                sys.exit(f"alias '{n}' used by {aliases[n]} and {m['id']}")
            aliases[n] = m["id"]
        if m.get("domain") not in ("G", "W", "M"):
            sys.exit(f"{m['id']}: domain must be G, W or M")
        if not (ROOT / "watch-app/resources/drawables/icons" / f"{m.get('icon')}.png").exists():
            sys.exit(f"{m['id']}: icon {m.get('icon')} not found (tools/make_icons.py)")
        if m.get("refTenths") is not None and not isinstance(m["refTenths"], int):
            sys.exit(f"{m['id']}: refTenths must be an int or null")
        c = m.get("counter")
        if c is not None:
            for k in ("alphaQ8", "hiMg", "loMg", "minGapMs"):
                if not isinstance(c.get(k), int):
                    sys.exit(f"{m['id']}: counter.{k} must be an int")
    return movements, aliases


def mc_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_js(movements, aliases) -> str:
    out = [f"// {HEADER}", ""]
    out.append("export const MOVEMENTS = {")
    for m in movements:
        out.append(
            f"  {m['id']}: {json.dumps({'name': m['name'], 'domain': m['domain'], 'refTenths': m.get('refTenths'), 'icon': m['icon'], 'counter': m.get('counter')})},"
        )
    out.append("};")
    out.append("")
    out.append("export const ALIASES = {")
    for k in sorted(aliases):
        out.append(f"  {json.dumps(k)}: {json.dumps(aliases[k])},")
    out.append("};")
    out.append("")
    return "\n".join(out)


def mc_entries(lines):
    """Join dictionary entries without a trailing comma on the last one."""
    return [l + ("," if i < len(lines) - 1 else "") for i, l in enumerate(lines)]


def gen_mc(movements, aliases) -> str:
    out = [f"// {HEADER}", "", "import Toybox.Lang;", "", "module MovementCatalog {", ""]
    out.append("    // normalized alias -> movement id")
    out.append("    function aliases() as Dictionary<String, String> {")
    out.append("        return {")
    out += mc_entries([f"            {mc_str(k)} => {mc_str(aliases[k])}" for k in sorted(aliases)])
    out.append("        } as Dictionary<String, String>;")
    out.append("    }")
    out.append("")
    out.append("    // movement id -> display name")
    out.append("    function names() as Dictionary<String, String> {")
    out.append("        return {")
    out += mc_entries([f"            {mc_str(m['id'])} => {mc_str(m['name'])}" for m in movements])
    out.append("        } as Dictionary<String, String>;")
    out.append("    }")
    out.append("")
    out.append("    // movement id -> domain: 0 gymnastics, 1 weightlifting, 2 monostructural")
    out.append("    function domains() as Dictionary<String, Number> {")
    out.append("        return {")
    out += mc_entries([f"            {mc_str(m['id'])} => {'GWM'.index(m['domain'])}" for m in movements])
    out.append("        } as Dictionary<String, Number>;")
    out.append("    }")
    out.append("")
    out.append("    // movement id -> icon name (resources/drawables/icons)")
    out.append("    function icons() as Dictionary<String, String> {")
    out.append("        return {")
    out += mc_entries([f"            {mc_str(m['id'])} => {mc_str(m['icon'])}" for m in movements])
    out.append("        } as Dictionary<String, String>;")
    out.append("    }")
    out.append("")
    out.append("    // movement id -> reference pace, tenths of a second per rep")
    out.append("    function refTenths() as Dictionary<String, Number> {")
    out.append("        return {")
    out += mc_entries([f"            {mc_str(m['id'])} => {m['refTenths']}" for m in movements if m.get("refTenths")])
    out.append("        } as Dictionary<String, Number>;")
    out.append("    }")
    out.append("")
    out.append("    // movement id -> [alphaQ8, hiMg, loMg, minGapMs] for auto rep counting")
    out.append("    function counterProfiles() as Dictionary<String, Array<Number> > {")
    out.append("        return {")
    out += mc_entries(
        [
            f"            {mc_str(m['id'])} => [{c['alphaQ8']}, {c['hiMg']}, {c['loMg']}, {c['minGapMs']}]"
            for m in movements
            if (c := m.get("counter"))
        ]
    )
    out.append("        } as Dictionary<String, Array<Number> >;")
    out.append("    }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main():
    movements, aliases = load()
    outputs = {JS_OUT: gen_js(movements, aliases), MC_OUT: gen_mc(movements, aliases)}
    check = "--check" in sys.argv
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        sys.exit("stale generated files: " + ", ".join(stale) + " (run python3 tools/gen_movements.py)")


if __name__ == "__main__":
    main()
