// Generate watch-app/test/ParserFixturesTest.mc from docs/fixtures, so the
// Monkey C parser is checked against the same expected output as the JS one.
// Run: node tools/gen_mc_tests.mjs   (CI runs it with --check)
import fs from "node:fs";
import path from "node:path";

const root = new URL("..", import.meta.url).pathname;
const dir = path.join(root, "docs/fixtures");
const out = path.join(root, "watch-app/test/ParserFixturesTest.mc");

const mcStr = (s) => '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n") + '"';
const mcVal = (v) => (v === null ? "null" : typeof v === "string" ? mcStr(v) : String(v));

let src = `// GENERATED by tools/gen_mc_tests.mjs from docs/fixtures. Do not edit.

import Toybox.Lang;
import Toybox.Test;

`;
for (const f of fs.readdirSync(dir).filter((f) => f.endsWith(".txt")).sort()) {
  const text = fs.readFileSync(path.join(dir, f), "utf8");
  const want = JSON.parse(fs.readFileSync(path.join(dir, f.replace(/\.txt$/, ".json")), "utf8"));
  const fn = "fixture_" + f.replace(/\.txt$/, "").replace(/[^a-z0-9]/gi, "_");
  src += `(:test)
function ${fn}(logger as Test.Logger) as Boolean {
    var r = WodParser.parse(${mcStr(text)});
    Test.assertMessage(r.hasKey("wod"), "parse error: " + r["error"]);
    var w = r["wod"] as Dictionary;
`;
  for (const k of ["name", "type", "timeCapSec", "intervalSec", "workSec", "restSec", "rounds", "repStep"]) {
    src += `    TestUtil.check(logger, w["${k}"], ${mcVal(want[k])}, "${k}");\n`;
  }
  if (want.repScheme) {
    src += `    TestUtil.checkArray(logger, w["repScheme"], [${want.repScheme.join(", ")}], "repScheme");\n`;
  } else {
    src += `    TestUtil.check(logger, w["repScheme"], null, "repScheme");\n`;
  }
  // optional keys: sets of AMRAP, every-minute task, men / women reps
  src += `    TestUtil.check(logger, w["sets"], ${mcVal(want.sets ?? null)}, "sets");\n`;
  src += `    TestUtil.check(logger, w["setRestSec"], ${mcVal(want.setRestSec ?? null)}, "setRestSec");\n`;
  src += `    TestUtil.check(logger, w["restAfterSec"], ${mcVal(want.restAfterSec ?? null)}, "restAfterSec");\n`;
  const blocksCheck = (arr, v, label) => {
    src += `    TestUtil.check(logger, ${v}.size(), ${arr.length}, "${label} count");\n`;
    arr.forEach((blk, i) => {
      for (const k of ["movement", "name", "reps", "unit", "slot"]) {
        src += `    TestUtil.check(logger, ${v}[${i}]["${k}"], ${mcVal(blk[k])}, "${label} ${i} ${k}");\n`;
      }
      if (blk.load) {
        src += `    TestUtil.checkArray(logger, ${v}[${i}]["load"], [${blk.load.join(", ")}], "${label} ${i} load");\n`;
      } else {
        src += `    TestUtil.check(logger, ${v}[${i}]["load"], null, "${label} ${i} load");\n`;
      }
      src += `    TestUtil.check(logger, ${v}[${i}]["repsAlt"], ${mcVal(blk.repsAlt ?? null)}, "${label} ${i} repsAlt");\n`;
    });
  };
  src += `    var b = w["blocks"] as Array<Dictionary>;\n`;
  blocksCheck(want.blocks, "b", "block");
  if (want.task) {
    src += `    var tk = w["task"] as Dictionary;\n`;
    src += `    TestUtil.check(logger, tk["everySec"], ${want.task.everySec}, "task everySec");\n`;
    src += `    TestUtil.check(logger, tk["at0"], ${want.task.at0}, "task at0");\n`;
    src += `    var tb = tk["blocks"] as Array<Dictionary>;\n`;
    blocksCheck(want.task.blocks, "tb", "task block");
  } else {
    src += `    TestUtil.check(logger, w["task"], null, "task");\n`;
  }
  src += `    return true;\n}\n\n`;
}

if (process.argv.includes("--check")) {
  if (!fs.existsSync(out) || fs.readFileSync(out, "utf8") !== src) {
    console.error("watch-app/test/ParserFixturesTest.mc is stale: run node tools/gen_mc_tests.mjs");
    process.exit(1);
  }
} else {
  fs.writeFileSync(out, src);
  console.log("wrote", path.relative(root, out));
}
